// src/IssueEditPage.jsx
import React, { useState } from 'react'
import { Link, useParams, useHistory } from 'react-router-dom'
import { useDispatch } from 'react-redux'
import { updateIssue } from './actions/issueActions'
import { getIssueById } from './selectors/issueSelectors'
import NotFoundPage from './NotFoundPage'

export default function IssueEditView() {

  const { id } = useParams()
  const issue = getIssueById(id)

  const [formData, setFormData] = useState(issue)
  const dispatch = useDispatch()
  const history = useHistory()

  function handleChange(e) {
    setFormData({ ...issue, [e.target.name]: e.target.value })
  }

  function handleSubmit(e) {
    e.preventDefault()
    dispatch(updateIssue(formData))
    history.push(`/issue/${issue.id}`)
  }

  return (
    <>
      {issue ? (
        <div className="container">
          <h1 className="title is-1">Edit an issue</h1>
          <form onSubmit={handleSubmit}>
            <div className="field">
              <label className="label">Title</label>
              <div className="control">
                <input name="title" className="input" type="text" required={true}
                       onChange={handleChange} value={formData.title} />
              </div>
            </div>

            <div className="field">
              <label className="label">Description</label>
              <div className="control">
            <textarea name="description" className="textarea"
                      onChange={handleChange} value={formData.description} />
              </div>
            </div>

            <div className="field is-grouped">
              <div className="control">
                <button className="button is-link">Save</button>
              </div>
              <div className="control">
                <Link to={`/issue/${issue.id}`} className="button is-link is-light">Cancel</Link>
              </div>
            </div>
          </form>
        </div>
      ) : (
        <NotFoundPage />
      )}
    </>
  )
}

// src/components/Pages/IssueEditPage.svelte
<script>
  import NotFoundPage from './NotFoundPage.svelte'
  import { findIssueById, saveIssue } from '../../stores/issues'
  import { writable } from 'svelte/store'

  export let params = {}
  const issue = findIssueById(params.id)
  let update = writable({ ...issue })

  function handleSubmit() {
    saveIssue({ ...issue, ...$update })
  }
</script>

{#if issue}
  <div class="container">
    <h1 class="title is-1">Edit an issue</h1>
    <form on:submit|preventDefault={handleSubmit}>
      <div class="field">
        <label class="label">Title</label>
        <div class="control">
          <input name="title" class="input" type="text" required bind:value={$update.title} />
        </div>
      </div>

      <div class="field">
        <label class="label">Description</label>
        <div class="control">
          <textarea name="description" class="textarea" bind:value={$update.description}></textarea>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <button class="button is-link">Save</button>
        </div>
        <div class="control">
          <a href="#/issue/{issue.id}" class="button is-link is-light">Cancel</a>
        </div>
      </div>
    </form>
  </div>
{:else}
  <NotFoundPage />
{/if}
