// src/IssueListPage.jsx
import React from 'react'
import classNames from 'classnames'
import { useDispatch, useSelector } from 'react-redux'
import { toggleIssue, deleteIssue } from './actions/issueActions'
import { Link } from 'react-router-dom'

export default function IssueListPage() {
  const issues = useSelector(state => state.issues)
  const dispatch = useDispatch()

  return (
    <div className="container">
      <h1 className="title is-1">Issues</h1>
      {issues.map(issue => (
        <div key={issue.id} className="card mb-4">
          <div className="card-content">
            <div className="columns">
              <div className="column">
                <label className="checkbox">
                  <input type="checkbox" className="mr-3" defaultValue={issue.complete}
                         onChange={() => dispatch(toggleIssue(issue))} />
                  <span className={classNames('is-size-5', !!issue.complete && 'is-strike')}>{issue.title}</span>
                </label>
              </div>
              <div className="column is-one-fifth">
                <div className="buttons">
                  <Link to={`/issue/${issue.id}`} className="button is-small is-light">Show</Link>
                  <Link to={`/issue/${issue.id}/edit`} className="button is-small is-light">Edit</Link>
                  <button className="button is-small is-light is-danger" onClick={() => dispatch(deleteIssue(issue))}>
                    Delete
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))}
      {issues.length === 0 && (
        <article className="message">
          <div className="message-body">
            No issues found, <Link to="/issues/new">create a new one</Link>
          </div>
        </article>
      )}
    </div>
  )
}

// src/pages/IssueListPage.svelte
<script>
  import issues, { toggleIssue, deleteIssue } from '../stores/issues'
</script>

<div class="container">
  <h1 class="title is-1">Issues</h1>
  {#each $issues as issue}
    <div class="card mb-4">
      <div class="card-content">
        <div class="columns">
          <div class="column">
            <label class="checkbox">
              <input type="checkbox" class="mr-3" bind:checked={issue.complete} on:change={() => toggleIssue(issue)} />
              <span class="is-size-5" class:is-strike={issue.complete}>{issue.title}</span>
            </label>
          </div>
          <div class="column is-one-fifth">
            <div class="buttons">
              <a href="#/issues/{issue.id}" class="button is-small is-light">Show</a>
              <a href="#/issues/{issue.id}/edit" class="button is-small is-light">Edit</a>
              <button class="button is-small is-light is-danger" on:click={() => deleteIssue(issue)}>
                Delete
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  {/each}
  {#if $issues.length === 0}
    <article class="message">
      <div class="message-body">
        No issues found,
        <a href="#/issues/new">create a new one</a>
      </div>
    </article>
  {/if}
</div>
