// src/components/Pages/IssueDetailPage.svelte
<script>
  import NotFoundPage from './NotFoundPage.svelte'
  import { findIssueById } from '../../stores/issues'

  export let params = {}
  const issue = findIssueById(params.id)
</script>

{#if issue}
  <div class="container">
    <h1 class="title is-1">{issue.title}</h1>
    <article class="content">
      <p>{issue.description}</p>
    </article>
  </div>
{:else}
  <NotFoundPage />
{/if}

// src/IssueDetailPage.jsx
import React from 'react'
import { useParams } from 'react-router-dom'
import { useSelector } from 'react-redux'
import NotFoundPage from './NotFoundPage'

export default function IssueDetailPage() {
  const { id } = useParams()
  const issue = useSelector(state => state.issues.filter(issue => issue.id === id)[0])

  return (
    <>
      {issue ? (
        <div className="container">
          <h1 className="title is-1">{issue.title}</h1>
          <article className="content">
            <p>{issue.description}</p>
          </article>
        </div>
      ) : (
        <NotFoundPage />
      )}
    </>
  )
}
