// src/NavigationBar.svelte
<script>
  // import NavigationSearchForm from './NavigationSearchForm'
  let opened = false
</script>

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <span class="is-size-4">🦟</span>
    </div>
    <a role="button" aria-label="menu" aria-expanded="false"
       class="navbar-burger burger" class:is-active={opened} on:click={() => opened = !opened}>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class="navbar-menu" class:is-active={opened}>
    <div class="navbar-start">
      <a href="#/issues/new" class="navbar-item">
        <span class="icon">
          <i class="fa fa-plus"></i>
        </span>
        {' '}
        <span>New issue</span>
      </a>
      <a href="#/issues" class="navbar-item">
        <span class="icon">
          <i class="fa fa-list"></i>
        </span>
        {' '}
        <span>Issues</span>
      </a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <!--        <NavigationSearchForm />-->
      </div>
    </div>
  </div>
</nav>

// src/NavigationBar.jsx
import React, { useState } from 'react'
import { NavLink } from 'react-router-dom'
import classNames from 'classnames'
import NavigationSearch from './NavigationSearch'

export default function NavigationBar() {
  const [open, setOpen] = useState(false)

  return (
    <nav className="navbar" role="navigation" aria-label="main navigation">
      <div className="navbar-brand">
        <div className="navbar-item">
          <span className="is-size-4">🦟</span>
        </div>
        <a role="button" aria-label="menu" aria-expanded="false" onClick={() => setOpen(!open)}
           className={classNames('navbar-burger', 'burger', open && 'is-active')}>
          <span aria-hidden="true" />
          <span aria-hidden="true" />
          <span aria-hidden="true" />
        </a>
      </div>
      <div className={classNames('navbar-menu', open && 'is-active')}>
        <div className="navbar-start">
          <NavLink exact to="/issues/new" className="navbar-item" activeClassName="is-active">
            <span className="icon">
              <i className="fa fa-plus" />
            </span>
            &nbsp;
            <span>New issue</span>
          </NavLink>
          <NavLink exact to="/issues" className="navbar-item" activeClassName="is-active">
            <span className="icon">
              <i className="fa fa-list" />
            </span>
            &nbsp;
            <span>Issues</span>
          </NavLink>
        </div>
        <div className="navbar-end">
          <div className="navbar-item">
            <NavigationSearch />
          </div>
        </div>
      </div>
    </nav>
  )
}
