// src/NavigationSearchForm.svelte
<script>
  import { writable } from 'svelte/store'
  import queryString from 'query-string'

  let formData = writable({ q: '' })

  // TODO: Fix search params
  function handleSubmit(e) {
    e.preventDefault()
    const query = queryString.stringify($formData)
    history.push(e.target.action + '?' + query)
  }
</script>

<form action="#/search" onSubmit={handleSubmit}>
  <div class="field">
    <div class="control has-icons-left has-icons-right">
      <input class="input" type="text" name="q" placeholder="Find an issue..."
             aria-label="Search an issue using a keyword" required bind:value={$formData.q} />
      <span class="icon is-small is-left">
        <i class="fas fa-search"></i>
      </span>
    </div>
  </div>
</form>

// src/NavigationSearchForm.jsx
import React, { useState } from 'react'
import queryString from 'query-string'
import { useHistory } from 'react-router-dom'

export default function NavigationSearchForm() {
  const [formData, setFormData] = useState({})
  const history = useHistory()

  function handleChange(e) {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  function handleSubmit(e) {
    e.preventDefault()
    const query = queryString.stringify(formData)
    history.push(`/search?${query}`)
  }

  return (
    <form action={`/search`} onSubmit={handleSubmit}>
      <div className="field">
        <div className="control has-icons-left has-icons-right">
          <input className="input" type="text" name="q" placeholder="Find an issue..."
                 required={true} onChange={handleChange} />
          <span className="icon is-small is-left">
            <i className="fas fa-search" />
          </span>
        </div>
      </div>
    </form>
  )
}
